# Generated by Django 5.1.6 on 2025-02-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_personaldetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalDetails',
        ),
    ]
