# Generated by Django 5.1.6 on 2025-02-12 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_personaldetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=80)),
                ('regid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mytable')),
            ],
        ),
    ]
