# Generated by Django 5.1.6 on 2025-02-13 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_personaldetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='media')),
                ('regid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mytable')),
            ],
        ),
    ]
